### ISSUE TITLE
FindJellyfish.cmake finds cereal, not jellyfish

### ISSUE THREAD

**Issue by rekado** [COMBINE-lab/RapMap#15]
The file `cmake/Modules/FindJellyfish.cmake` is satisfied when it finds the cereal includes.  I don't have Jellyfish installed and was surprised that CMake reported that it found Jellyfish.  It simply printed the path to the cereal headers.

**Comment by rob-p** [comment]
Indeed — I'm not sure how that problem crept in to begin with, but the latest commit should address it.  There is no standard `FindJellyfish.cmake`, so the one provided here should just attempt to do the obvious thing without being too clever (I imagine it could fail to find an installed jellyfish if it was in a non-standard location).  Thanks for reporting this.

**Comment by rekado** [comment]
Thank you.  I'm trying to package up sailfish and salmon for GNU Guix.  To make this work I need to first package up RapMap (even though there hasn't been released) as we cannot just download dependencies from the Internet at build time.

**Comment by rob-p** [comment]
Ahh; cool!  The plan is to have Sailfish & Salmon rely on RapMap as a versioned dependency, but that will only happen once we have a versioned release of RapMap (this should be soon, hopefully).
