### ISSUE TITLE
How to determine the length of k-mer to index ?

### ISSUE THREAD

**Issue by CTLife** [COMBINE-lab/RapMap#16]
rapmap  quasiindex  --help:                     
-k    (positive integer less than 32),     --klen   (positive integer less than32),       The length of k-mer to index.                       

But how to select the k for different genome, such as human, mouse and c.elegans ?

Thank you.

**Comment by rob-p** [comment]
Hi @CTLife,

  The default value of 31 should work well for a wide range of organisms and read lengths.  The only reason you might consider selecting a smaller value is to reduce memory usage (if you have e.g. a particularly huge *de novo* transcriptome), or if you're dealing with very short reads (e.g. <50 bases).

  P.S.  You mention *genomes* above, but please note that RapMap is designed for alignment to a transcriptome (a FASTA of all of the transcripts / RNA-products to which you wish to map).  We strongly advise against building the index on the genome itself.

**Comment by CTLife** [comment]
Ok, thank you @rob-p ,
      I will rebuild the index by using transcriptome.

**Comment by rob-p** [comment]
No problem, @CTLife!  Let us know if you have any other questions.
