### ISSUE TITLE
What is the mean of reference transcriptome fasta sequence ?

### ISSUE THREAD

**Issue by CTLife** [COMBINE-lab/RapMap#17]
Hi,
What is the mean of reference transcriptome fasta sequence ?
Unspliced Gene sequence (DNA) ?   or cDNA sequences ? or other ?
Can you give me a example ?
Thank You.

**Comment by rob-p** [comment]
The cDNA sequence.  For example, if you were interested in mapping to the Ensembl annotation (say, for human), you'd use [this](ftp://ftp.ensembl.org/pub/release-83/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh38.cdna.all.fa.gz) file.

**Comment by CTLife** [comment]
OK. thank you.
