### ISSUE TITLE
Add support for Salmon library types

### ISSUE THREAD

**Issue by rob-p** [COMBINE-lab/RapMap#2]
It would be nice to allow RapMap to mark alignments as concordant or discordant --- right now it has no idea of these concepts.

**Comment by mdshw5** [comment]
Is there any plan to add `QuasiAlignment` output as an option for Salmon? I understand that this would be off by default, but would be useful as an option...

**Comment by rob-p** [comment]
This could be done fairly easily I think.  There are two places I see this being useful.  One is just to have the set of all quasi-mappings found by Salmon so you know what it was working with.  The other related feature (I think @Blahah would be interested in this) would be to output *disambiguated* quasi-mappings after quantification has happened.  This requires a second quasi-mapping pass through the reads (since remembering all mappings would waste too much space), but it would give you a nice set of alignments — one target per read — where the probability of assigning a multimapping read to a target is proportional to that target's inferred abundance.  Salmon can already do with with alignments from a bam file, and it's useful in certain cases.

**Comment by Blahah** [comment]
+1x10^999999...

**Comment by rob-p** [comment]
@Blahah — would the current RapMap output format (target / position / strand, encoded in SAM format) be useful to you at all yet, or would you need the full-blown alignment before this becomes useful?

**Comment by Blahah** [comment]
We need some way to know the number of mismatches between the read and the target. Can that be calculated from the information already available without doing an alignment?

**Comment by rob-p** [comment]
@Blahah — not really.  For example, we know the number and length of exactly matching intervals (maximum mappable prefixes) between the read and reference, but not what occurs in between.  This means it would be possible to miss some matches.  However, as we discussed before, actually providing the alignment should not be very difficult; it just hasn't been implemented yet.  However, seeing the pain the aligner causes in Transrate, I'd like to make it an action item.
