### ISSUE TITLE
Please state clear license and copyright 

### ISSUE THREAD

**Issue by satta** [COMBINE-lab/RapMap#31]
I'm currently packaging RapMap for Debian and I was wondering if you could add a license statement (e.g. mentioning the GPL version used for now, etc. -- I am currently assuming it will be GPLv3 as in Jellyfish) as well as some indication of copyright attribution for the main RapMap tool. This would make it possible to include the tool in the Debian archive -- thanks. Ideally there would also be a new tagged release ;)

**Comment by rob-p** [comment]
Hi @satta,

  I've added a license (GPLv3 in License.md).  Further, in the develop-salmon branch, which I will be merging back into master to make the next tagged release, I've added the appropriate headers with copyright info to the source.  I hope to get out a new tagged release in the next few days.  Thanks for pinging me on the license etc.

**Comment by satta** [comment]
Great, thanks! Waiting for the new release.
BTW, I would also kindly ask for your thoughts on https://github.com/COMBINE-lab/salmon/issues/87 which addresses the connection between RapMap and salmon.

**Comment by rob-p** [comment]
Hi @satta,

  Sorry for the delay, but there were a few features that I really wanted to get into the latest release (v0.4.0).  You can check the change log of what was added / modified in the [release notes](https://github.com/COMBINE-lab/RapMap/releases/tag/v0.4.0).

--Rob
