### ISSUE TITLE
Are there windows binaries?

### ISSUE THREAD

**Issue by eead-csic-compbio** [COMBINE-lab/RapMap#34]
Hi, we are currently learning to use RapMap and SailFish and would like to know if someone has succeeded compiling and linking to the libraries under lib/ under Windows. Thanks for the great software,
Bruno

**Comment by rob-p** [comment]
Hi Bruno,

  We currently do not provide any binaries for these tools under windows, as we don't have access to windows machines (also, maintaining the builds under Linux, which accounts for almost all of our user base, and OSX, is already a bit of a maintenance burden).  I know that James Lloyd (@JamesPBLloyd on Twitter) has gotten [Salmon](https://github.com/COMBINE-lab/salmon) to run under the "unix environment" in Windows 10.  Given the shared codebase, I'd imagine that it is equally possible to get RapMap and Sailfish to work under that setup.  However, as far as a *native* Windows binary, it may be possible, but there are probably a number of changes that would need to be made to the code to properly support windows (e.g. interaction with the filesystem etc.).

--Rob
