### ISSUE TITLE
Transcriptome clustering

### ISSUE THREAD

**Issue by hmontenegro** [COMBINE-lab/RapMap#37]
I want to repeat the analysis from section "5 Application of quasi-mapping for clustering de novo assemblies", from the paper "RapMap: a rapid, sensitive and accurate tool for mapping RNA-seq reads to transcriptomes. Bioinformatics (2016) 32 (12): i192-i200".

The paper states RapMap was used, but I can't find documentation on how to do the clustering with RapMap. I also found RapCluster github repo. Using SailFish + RapClust gives the same results as the paper?

**Comment by hiraksarkar** [comment]
Hi, 

Thanks for your interest. 

Rapclust was an extension of section 5 in RapMap. I would suggest check out the repo for the data. README.md explained the data well there. I am closing this issue and request you to open another issue in https://github.com/COMBINE-lab/RapClust if you still face problems to curate the data. 

Thanks
