### ISSUE TITLE
Output NH tag in SAM output

### ISSUE THREAD

**Issue by vals** [COMBINE-lab/RapMap#8]
I just tried the 'quasialignment' (SA based) and it is positively amazing! (~15 seconds per sample to map)

Would it be possible to output an NH tag in the SAM output which tells how many locations a read maps to?

**Comment by rob-p** [comment]
Hi @vals --- I'm glad you may find a use for RapMap.  We're also somewhat amazed by the speed with which it seems possible to attack this problem.  It should be fairly easy to add this tag to the current output.  I'm assigning this issue to myself and will comment here when I've implemented this feature.

**Comment by rob-p** [comment]
Ok, I've added the NH flag to the output alignments, so I'm going to close this issue for now.  However, feel free to comment / re-open if necessary.
